/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jeff' at '9/20/16 11:53 PM' with Gradle 3.1
 *
 * @author jeff, @date 9/20/16 11:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
